config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]

  resource :users,
      only: [:edit, :update, :destroy],
      controller: 'devise/registrations',
      as: :user_registration do
    get 'cancel'
  end

  root to: 'cards#index'
  resources :cards, only: :index
  resources :board_stats, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord

  def self.fetch_trello_cards
    url = "https://api.trello.com/1/boards/5ec56063edc3f53f0c17f299/cards?key=#{ENV['TRELLO_KEY']}&token=#{ENV['TRELLO_TOKEN']}"
    uri = URI(url)
    response = Net::HTTP.get(uri)
    cards_array = separate_description_array(JSON.parse(response))
    cards_array.each do |card|
      secretary_name(card)
    end
  end

  def self.sort_by_date(cards_array)
    cards_array = cards_array.sort_by { |hash| hash["dateLastActivity"] }.reverse!
  end

  def self.secretary_filter(cards, params)
    secretaria = params["secretaria"]
    cards = cards.select { |card| card["custom_info"]["Secretaría"] == secretaria }
  end

  private

  def self.separate_description_array(cards_array)
    cards_array.each do |hash|
      desc_hash = {}
      hash["desc"].gsub("**", "").gsub("\n\n", "\n").split("\n").each do |element|
        hash["custom_info"] = create_description_hash(element, desc_hash)
      end
    end
    cards_array
  end

  def self.create_description_hash(element, desc_hash)
    return if element.empty?

    description_item_array = element.split(":", 2)
    desc_hash["#{description_item_array.first.strip}"] = description_item_array.last.strip
    desc_hash
  end

  def self.secretary_name(card)
    @secretary_name = card["custom_info"]["Secretaría"]
    return if @secretary_name.nil?

    @secretary_name = @secretary_name.titleize
    convert_da if @secretary_name.include? ("Departamento Administrativo")
    convert_dapard if @secretary_name.include? ("Dapard")
    card["custom_info"]["Secretaría"] = @secretary_name
  end

  private

  def self.convert_da
    @secretary_name = @secretary_name.gsub("Departamento Administrativo", "D.A.")
    @secretary_name
  end

  def self.convert_dapard
    @secretary_name = @secretary_name.gsub("Dapard", "DAPARD")
    @secretary_name
  end
end

app/models/list.rb
class List < ApplicationRecord

  def self.fetch_trello_list
    board_id = "5ec56063edc3f53f0c17f299"
    url = "https://api.trello.com/1/boards/#{board_id}/lists?key=#{ENV['TRELLO_KEY']}&token=#{ENV['TRELLO_TOKEN']}"
    uri = URI(url)
    response = Net::HTTP.get(uri)
    JSON.parse(response)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.fetch_trello_members
    board_id = "5ec56063edc3f53f0c17f299"
    url = "https://api.trello.com/1/boards/#{board_id}/members?key=#{ENV['TRELLO_KEY']}&token=#{ENV['TRELLO_TOKEN']}"
    uri = URI(url)
    response = Net::HTTP.get(uri)
    JSON.parse(response)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/board_stats_controller.rb
class BoardStatsController < ApplicationController
  # skip_before_action :authenticate_user!
  before_action :set_filtered_cards

  def index
    @members = User.fetch_trello_members
    @lists = List.fetch_trello_list
  end

  private

  def set_filtered_cards
    @cards = Card.sort_by_date(Card.fetch_trello_cards)
    @secretarias = secretarias_array
    return @cards if params.empty?

    @cards = Card.secretary_filter(@cards, params.slice(:secretaria)) unless params["secretaria"].nil?
  end

  def secretarias_array
    @cards.reject { |card| card["custom_info"]["Secretaría"].nil?}
          .map!   { |card| card["custom_info"]["Secretaría"] }
          .uniq
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_filtered_cards

  def index
    @members = User.fetch_trello_members
    @lists = List.fetch_trello_list
  end

  private

  def set_filtered_cards
    @cards = Card.sort_by_date(Card.fetch_trello_cards)
    @secretarias = secretarias_array
    return @cards if params.empty?

    @secretarias = secretarias_array
    @cards = Card.secretary_filter(@cards, params.slice(:secretaria)) unless params["secretaria"].nil?
  end

  def secretarias_array
    @cards.reject { |card| card["custom_info"]["Secretaría"].nil?}
          .map!   { |card| card["custom_info"]["Secretaría"] }
          .uniq
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_filter(params)
    return "Secretarías" if params["secretaria"].nil?

    params["secretaria"]
  end

  def list_for_card(card)
    @lists.find {|key, value| key["id"] == card["idList"]}
  end

  def toggle_active_class(element)
    return "active" if controller_name == element
    ""
  end
end

app/helpers/board_stats_helper.rb
module BoardStatsHelper

  def status_hash
    status_hash = Hash.new(0)
    @cards.each { |card| status_hash["#{list_for_card(card)["name"]}"] += 1 }
    status_hash
  end

  def pluralize(hash, key)
    hash[key] == 1 ? key : "#{key}s"
  end

  def secretarias_hash
    secretarias_hash = Hash.new(0)
    @cards.each do |card|
      if card["custom_info"]["Secretaría"].nil?
        secretarias_hash["Sin asignar"] += 1
      else
        secretarias_hash[card["custom_info"]["Secretaría"]] += 1
      end
    end
    secretarias_hash
  end

  def average_by_period_time(period = "days")
    @period_range = set_period_range(period)

    compute_ratio(counter_by_date(@cards), @days)
  end

  def calculate_ratio_by_period(status, period = "days")
    @period_range = set_period_range(period)
    counter = counter_by_date(@cards)
    factor = counter.positive? ? 100 : 1
    percentage = counter.positive? ? "%" : ""

    filtered_cards = @cards.select do |card|
      list_for_card(card)["name"] == status
    end

    "#{compute_ratio(counter_by_date(filtered_cards), counter, factor)}#{percentage} "
  end

  def count_totals(period = "days")
    @period_range = set_period_range(period)
    counter_by_date(@cards)
  end

  private

  def set_period_range(period)
    start_date = 7.send(period).ago.to_date
    end_date   = 0.send(period).ago.to_date
    @days = (end_date - start_date).to_f

    start_date..end_date
  end

  def counter_by_date(cards)
    @period_range.inject(0) do |sum, date|
      sum + cards.select{ |card| card["custom_info"]["Fecha de solicitud"].to_date == date }.size
    end
  end

  def compute_ratio(dividen, divisor, factor = 1)
    return "Na" unless divisor > 0

    (dividen / divisor.to_f * factor).round(2)
  end
end

app/helpers/cards_helper.rb
module CardsHelper

  def convert_utc_date_to_local(string_date)
    string_date.to_datetime.in_time_zone("Bogota").to_date unless string_date.nil?
  end

  def status_color(list_name)
    return "#DF3B46" if list_name == "Nuevas solicitudes"
    return "#DF3B46" if list_name == "Recibida"
    return "#FACD3A" if list_name == "Revisada"
    return "#00A878" if list_name == "Accionada"
    return "#545D63"
  end

  def card_responsable(card, board_members)
    card_members = card["idMembers"]
    card_members_names = []

    card_members.each do |card_member|
      board_members.each do |board_member|
        card_members_names << board_member["fullName"] if board_member["id"] == card_member
      end
    end
    card_members_names.join("")
  end

  def cut_card_secretary(secretary_name)
    return secretary_name if secretary_name.size < 29

    "#{secretary_name[0..29]}..."
  end
end

app/views/board_stats/index.html.erb
<div class="container">
  <div class="filters pt-2 pt-sm-4">
    <button class="btn btn-filters" type="button"
            data-toggle="collapse"
            data-target="#collapseFilters"
            aria-expanded="false"
            aria-controls="collapseFilters">

      <span class="d-flex align-items-center justify-content-around">
        <%= active_filter(params)  %>
        <%= image_tag 'icons/down-arrow.svg', width: 12, height: 12 %>
      </span>
    </button>
    <div class="collapse" id="collapseFilters">
      <div class="card card-body">
        <%= render "shared/filter-link", secretarias: @secretarias %>
      </div>
    </div>
  </div>
  <div class="graph-card">
    <%= render "shared/graphs/main-cards", status_hash: status_hash %>
  </div>
  <div class="graph-card card p-2">
    <%= render "shared/graphs/solicitudes-distribution", secretarias_hash: secretarias_hash %>
  </div>
  <div class="graph-card card p-2">
    <%= render "shared/graphs/summary-table", status_hash: status_hash %>
  </div>
</div>

app/views/cards/_card.html.erb
<card class="card">
  <div class="grid">
    <div class="card-content p-3">
      <div class="card-objective d-flex align-items-center mb-3">
        <div class="icon pr-2">
          <%= image_tag('icons/aim.svg', width: 24, height: 24) %>
        </div>
        <%= card["name"] %>
      </div>
      <div class="text-center">
        <div class="card-secretary">
          <%= card["custom_info"]["Secretaría"] %>
        </div>
        <div class="card-subtitle">
          <%= card["custom_info"]["Dependencia"]  %>
        </div>
        <div class="card-fecha-solicitud card-task-detail">
          Fecha de solicitud: <%= convert_utc_date_to_local(card["custom_info"]["Fecha de solicitud"]) %>
        </div>
      </div>
      <div class="card-bottom mt-3">
        <div class="d-flex justify-content-between mt-3">
          <div class="card-bottom-left">
            <div class="d-flex estado mb-1 align-items-center">
              <div class="icon pr-2">
                <%= image_tag('icons/flag.svg', width: 20, height: 20) %>
              </div>
              <div class="card-info">
                <div class="help-text">
                  Estado:
                </div>
                <div class="card-task-detail">
                  <%= list["name"] %>
                </div>
              </div>
            </div>
            <div class="col-xs-6 d-flex solicitante align-items-center">
              <div class="icon pr-2">
                <%= image_tag('icons/people.svg', width: 20, height: 20) %>
              </div>
              <div class="card-info">
                <div class="help-text">
                  Solicitante:
                </div>
                <div class="card-person-name card-task-detail">
                   <%= card["custom_info"]["Funcionario"].split('@')[0]  %>
                </div>
              </div>
            </div>
          </div>
          <div class="card-bottom-rigt">
            <div class="d-flex fecha-cambio mb-1 align-items-center">
              <div class="icon pr-2">
                <%= image_tag('icons/calendar.svg', width: 20, height: 20) %>
              </div>
              <div class="card-info">
                <div class="help-text">
                  Fecha cambio estado:
                </div>
                <div class="card-task-detail">
                  <%= convert_utc_date_to_local(card["dateLastActivity"])  %>
                </div>
              </div>
            </div>
            <div class="col-xs-6 d-flex responsable align-items-center">
              <div class="icon pr-2">
                <%= image_tag('icons/person.svg', width: 20, height: 20) %>
              </div>
              <div class="card-info">
                <div class="help-text">
                  Responsable:
                </div>
                <div class="card-person-name card-task-detail">
                  <%= card_responsable(card, @members) %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card-status-color" style="background-color: <%= status_color(list["name"]) %>;" >
    </div>
  </div>
</card>

app/views/cards/index.html.erb
<div class="container">
  <div class="filters pt-2 pt-sm-4">
    <button class="btn btn-filters" type="button"
            data-toggle="collapse"
            data-target="#filterCollapse"
            aria-expanded="false"
            aria-controls="filterCollapse">

      <span class="d-flex align-items-center justify-content-around">
        <%= active_filter(params) %>
        <%= image_tag 'icons/down-arrow.svg', width: 12, height: 12 %>
      </span>
    </button>
    <div class="collapse" id="filterCollapse">
      <div class="card card-body">
        <%= render "shared/filter-link", secretarias: @secretarias %>
      </div>
    </div>
  </div>
  <div class="row">
    <% @cards.each do |card| %>
      <div class="col-xs-12 col-sm-6">
        <%= render "card", { card: card, list: list_for_card(card) } %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Seguimiento Solicitudes Dirección de Informática</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/chart.js@2.9.1/dist/Chart.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.1/dist/Chart.min.js"></script>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_filter-link.html.erb
<% if controller_name == "cards" %>
  <%= link_to "Ver todas", cards_path, class:"dropdown-item" %>
  <% @secretarias.sort.each do |sec| %>
    <%= link_to cards_path(secretaria: sec), class:"dropdown-item" do %>
      <%= cut_card_secretary(sec) %>
    <% end %>
  <% end %>
<% elsif controller_name == "board_stats" %>
  <%= link_to "Ver todas", board_stats_path, class:"dropdown-item" %>
  <% @secretarias.each do |sec| %>
    <%= link_to sec, board_stats_path(secretaria: sec), class:"dropdown-item" %>
  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-gob"
     data-controller="navbar">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "logo_gob.jpg" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item <%= toggle_active_class('cards')  %>"
            data-target="navbar.li"
            data-action="click->navbar#toggleActiveClass">
            <%= link_to "Feed", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item  <%= toggle_active_class('board_stats')  %>"
            data-target="navbar.li"
            data-action="click->navbar#toggleActiveClass">
            <%= link_to "Estadísticas", board_stats_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Iniciar Sesión", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/graphs/_main-cards.html.erb
<h5 class="card-title text-center mb-2">Estado de solicitudes</h5>
<div class="stats-main-cards">
  <div class="row">
    <div class="col-6 col-md-3 mt-2 mb-2">
      <div class="card stats-card m-0 ">
        <h2>
          <%= status_hash["Accionada"]  %>
        </h2>
        <div class="card-text">
          <%= pluralize(status_hash, "Accionada") %>
        </div>
        <div class="card-status-color stats-card-status card-background-green" >
        </div>
      </div>
    </div>
    <div class="col-6 col-md-3 mt-2 mb-2">
      <div class="card stats-card m-0 ">
        <h2>
          <%= status_hash["Nueva solicitud"] + status_hash["Recibida"] + status_hash["Revisada"] %>
        </h2>
        <div class="card-text">
          <%= pluralize(status_hash, "Pendiente") %>
        </div>
        <div class="card-status-color stats-card-status card-background-yellow" >
        </div>
      </div>
    </div>
    <div class="col-6 col-md-3 mt-2">
      <div class="card stats-card m-0 ">
        <h2>
          <%= status_hash["Rechazada"]  %>
        </h2>
        <div class="card-text">
          <%= pluralize(status_hash, "Rechazada") %>
        </div>
        <div class="card-status-color stats-card-status card-background-red" >
        </div>
      </div>
    </div>
    <div class="col-6 col-md-3 mt-2">
      <div class="card stats-card m-0 ">
        <h2>
          <%= @cards.size %>
        </h2>
        <div class="card-text">
          En total
        </div>
        <div class="card-status-color stats-card-status card-background-gray">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/graphs/_solicitudes-distribution.html.erb
<h5 class="card-title text-center mb-2">Distribución de solicitudes</h5>
<canvas id="distribution" width="960" height="500"></canvas>
<% labels = secretarias_hash.keys %>
<% values = secretarias_hash.values %>
<script>
  const ctx = document.getElementById('distribution');
  const myChart = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: <%= labels.to_json.html_safe %>,
      datasets: [{
        data: <%= values.to_json.html_safe %>,
        backgroundColor: ['rgba(255, 99, 132, 0.2)', 'rgba(54, 162, 235, 0.2)', 'rgba(255, 206, 86, 0.2)', 'rgba(75, 192, 192, 0.2)', 'rgba(153, 102, 255, 0.2)', 'rgba(255, 159, 64, 0.2)'],
        borderColor: ['rgba(255, 99, 132, 1)', 'rgba(54, 162, 235, 1)', 'rgba(255, 206, 86, 1)', 'rgba(75, 192, 192, 1)', 'rgba(153, 102, 255, 1)', 'rgba(255, 159, 64, 1)'],
        borderWidth: 1
      }]
    },
    options: {
      legend: {
          display: false
      },
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: true,
            stepSize: 1,
            max: <%= values.max + 1 %>
          }
        }]
      }
    }
  });
</script>

app/views/shared/graphs/_summary-table.html.erb
<div class="text-center mb-2">
  <h5 class="card-title ">Resumen de solicitudes</h5>
  <div class="card-explanatory-title">
   Desde el <%= 7.send("weeks").ago.to_date  %>
  </div>
</div>
<div class="stat-line">
  <hr>
  <div class="d-flex justify-content-between stat-row">
    <div class="stat-description">
      Total Solicitudes
    </div>
    <div class="stat-value">
      <%= count_totals("weeks")  %>
    </div>
  </div>
  <hr>
</div>
<div class="stat-line">
  <div class="d-flex justify-content-between stat-row">
    <div class="stat-description">
      Promedio Solicitudes / día
    </div>
    <div class="stat-value">
      <%= average_by_period_time("weeks") %>
    </div>
  </div>
  <hr>
</div>
<div class="stat-line">
  <div class="d-flex justify-content-between stat-row">
    <div class="stat-description">
      Porcentaje de ejecución
    </div>
    <div class="stat-value">
      <%= calculate_ratio_by_period("Accionada", "weeks") %>
    </div>
  </div>
  <hr>
</div>
<div class="stat-line">
  <div class="d-flex justify-content-between stat-row">
    <div class="stat-description">
      Porcentaje de rechazo
    </div>
    <div class="stat-value">
      <%= calculate_ratio_by_period("Rechazada", "weeks") %>
    </div>
  </div>
  <hr>
</div>

app/views/shared/graphs/_test.html.erb
<canvas id="myChart" width="960" height="500"></canvas>
<script>
  var ctx = document.getElementById('myChart');
  var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
      datasets: [{
        label: '# of Votes',
        data: [12, 19, 3, 5, 2, 3],
        backgroundColor: ['rgba(255, 99, 132, 0.2)', 'rgba(54, 162, 235, 0.2)', 'rgba(255, 206, 86, 0.2)', 'rgba(75, 192, 192, 0.2)', 'rgba(153, 102, 255, 0.2)', 'rgba(255, 159, 64, 0.2)'],
        borderColor: ['rgba(255, 99, 132, 1)', 'rgba(54, 162, 235, 1)', 'rgba(255, 206, 86, 1)', 'rgba(75, 192, 192, 1)', 'rgba(153, 102, 255, 1)', 'rgba(255, 159, 64, 1)'],
        borderWidth: 1
      }]
    },
    options: {
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: true
          }
        }]
      }
    }
  });
</script>